controller_manager:

  ros__parameters:

    update_rate: 20  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_status_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  
  ros__parameters:

    type: joint_state_broadcaster/JointStateBroadcaster
    
    joints:
      - head_p
      - head_y
      - l_sho_p
      - l_sho_r
      - l_elb_y
      - l_elb_p
      - r_sho_p
      - r_sho_r
      - r_elb_y
      - r_elb_p

    interfaces:
      - position
      - velocity
      - effort

joint_status_broadcaster:

  ros__parameters:

    type: joint_state_broadcaster/JointStateBroadcaster
    update_rate: 1  # Hz
    
    joints:
      - head_p
      - head_y
      - l_sho_p
      - l_sho_r
      - l_elb_y
      - l_elb_p
      - r_sho_p
      - r_sho_r
      - r_elb_y
      - r_elb_p

    interfaces:
      - temperature
      - voltage
      - torque_enable
      - error_overload
      - error_electrical_shock
      - error_motor_encoder
      - error_overheating
      - error_input_voltage
      - led
